[book]
authors = ["Paul Loyd"]
language = "en"
multilingual = false
src = "src"
title = "The Actoromicon"

[rust]
edition = "2018"

[output.html]
mathjax-support = true
additional-css = ["custom.css"]
